fix for
Traceback (most recent call last):
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 1472, in traceback
    await self.bot.send_interactive(
  File "/root/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 2468, in send_interactive
    not channel.guild or channel.permissions_for(channel.guild.me).attach_files
                         ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Member' object has no attribute 'permissions_for'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Member' object has no attribute 'permissions_for'